# Generated by Django 5.1.1 on 2024-09-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('subcategory_image', models.ImageField(null=True, upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comm.tbl_category')),
            ],
        ),
    ]
