# Generated by Django 5.1.1 on 2024-10-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0006_tbl_checkout_tbl_checkout_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_checkout',
            name='country',
        ),
    ]
