# Generated by Django 5.1.1 on 2024-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0008_rename_check_out_tbl_checkout_products_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
